In [64]:
import pandas as pd

In [65]:
oly = pd.read_csv("./data/olympics.csv",skiprows=4)

In [66]:
oly

,City,Edition,Sport,Discipline,Athlete,NOC,Gender,Event,Event_gender,Medal
0,Athens,1896,Aquatics,Swimming,"HAJOS, Alfred",HUN,Men,100m freestyle,M,Gold
1,Athens,1896,Aquatics,Swimming,"HERSCHMANN, Otto",AUT,Men,100m freestyle,M,Silver
2,Athens,1896,Aquatics,Swimming,"DRIVAS, Dimitrios",GRE,Men,100m freestyle for sailors,M,Bronze
3,Athens,1896,Aquatics,Swimming,"MALOKINIS, Ioannis",GRE,Men,100m freestyle for sailors,M,Gold
4,Athens,1896,Aquatics,Swimming,"CHASAPIS, Spiridon",GRE,Men,100m freestyle for sailors,M,Silver
...,...,...,...,...,...,...,...,...,...,...
29211,Beijing,2008,Wrestling,Wrestling Gre-R,"ENGLICH, Mirko",GER,Men,84 - 96kg,M,Silver
29212,Beijing,2008,Wrestling,Wrestling Gre-R,"MIZGAITIS, Mindaugas",LTU,Men,96 - 120kg,M,Bronze
29213,Beijing,2008,Wrestling,Wrestling Gre-R,"PATRIKEEV, Yuri",ARM,Men,96 - 120kg,M,Bronze
29214,Beijing,2008,Wrestling,Wrestling Gre-R,"LOPEZ, Mijain",CUB,Men,96 - 120kg,M,Gold
29215,Beijing,2008,Wrestling,Wrestling Gre-R,"BAROEV, Khasan",RUS,Men,96 - 120kg,M,Silver

In [67]:
oly.loc[4]

City                                Athens
Edition                               1896
Sport                             Aquatics
Discipline                        Swimming
Athlete                 CHASAPIS, Spiridon
NOC                                    GRE
Gender                                 Men
Event           100m freestyle for sailors
Event_gender                             M
Medal                               Silver
Name: 4, dtype: object

In [83]:
oly.iloc[lambda x: x.index % 3 == 0]

,NOC,City,Edition,Sport,Discipline,Athlete,Gender,Event,Event_gender,Medal
0,HUN,Athens,1896,Aquatics,Swimming,"HAJOS, Alfred",Men,100m freestyle,M,Gold
3,GRE,Athens,1896,Aquatics,Swimming,"MALOKINIS, Ioannis",Men,100m freestyle for sailors,M,Gold
6,HUN,Athens,1896,Aquatics,Swimming,"HAJOS, Alfred",Men,1200m freestyle,M,Gold
9,AUT,Athens,1896,Aquatics,Swimming,"NEUMANN, Paul",Men,400m freestyle,M,Gold
12,HUN,Athens,1896,Athletics,Athletics,"SZOKOLYI, Alajos",Men,100m,M,Bronze
...,...,...,...,...,...,...,...,...,...,...
29202,BUL,Beijing,2008,Wrestling,Wrestling Gre-R,"YANAKIEV, Yavor",Men,66 - 74kg,M,Bronze
29205,TUR,Beijing,2008,Wrestling,Wrestling Gre-R,"AVLUCA, Nazmi",Men,74 - 84kg,M,Bronze
29208,KAZ,Beijing,2008,Wrestling,Wrestling Gre-R,"MAMBETOV, Asset",Men,84 - 96kg,M,Bronze
29211,GER,Beijing,2008,Wrestling,Wrestling Gre-R,"ENGLICH, Mirko",Men,84 - 96kg,M,Silver
29214,CUB,Beijing,2008,Wrestling,Wrestling Gre-R,"LOPEZ, Mijain",Men,96 - 120kg,M,Gold

In [68]:
oly.set_index('NOC', inplace=True)

In [69]:
oly

,City,Edition,Sport,Discipline,Athlete,Gender,Event,Event_gender,Medal
NOC,,,,,,,,,
HUN,Athens,1896,Aquatics,Swimming,"HAJOS, Alfred",Men,100m freestyle,M,Gold
AUT,Athens,1896,Aquatics,Swimming,"HERSCHMANN, Otto",Men,100m freestyle,M,Silver
GRE,Athens,1896,Aquatics,Swimming,"DRIVAS, Dimitrios",Men,100m freestyle for sailors,M,Bronze
GRE,Athens,1896,Aquatics,Swimming,"MALOKINIS, Ioannis",Men,100m freestyle for sailors,M,Gold
GRE,Athens,1896,Aquatics,Swimming,"CHASAPIS, Spiridon",Men,100m freestyle for sailors,M,Silver
...,...,...,...,...,...,...,...,...,...
GER,Beijing,2008,Wrestling,Wrestling Gre-R,"ENGLICH, Mirko",Men,84 - 96kg,M,Silver
LTU,Beijing,2008,Wrestling,Wrestling Gre-R,"MIZGAITIS, Mindaugas",Men,96 - 120kg,M,Bronze
ARM,Beijing,2008,Wrestling,Wrestling Gre-R,"PATRIKEEV, Yuri",Men,96 - 120kg,M,Bronze
CUB,Beijing,2008,Wrestling,Wrestling Gre-R,"LOPEZ, Mijain",Men,96 - 120kg,M,Gold
RUS,Beijing,2008,Wrestling,Wrestling Gre-R,"BAROEV, Khasan",Men,96 - 120kg,M,Silver

In [70]:
oly.loc['GRE']

,City,Edition,Sport,Discipline,Athlete,Gender,Event,Event_gender,Medal
NOC,,,,,,,,,
GRE,Athens,1896,Aquatics,Swimming,"DRIVAS, Dimitrios",Men,100m freestyle for sailors,M,Bronze
GRE,Athens,1896,Aquatics,Swimming,"MALOKINIS, Ioannis",Men,100m freestyle for sailors,M,Gold
GRE,Athens,1896,Aquatics,Swimming,"CHASAPIS, Spiridon",Men,100m freestyle for sailors,M,Silver
GRE,Athens,1896,Aquatics,Swimming,"CHOROPHAS, Efstathios",Men,1200m freestyle,M,Bronze
GRE,Athens,1896,Aquatics,Swimming,"ANDREOU, Joannis",Men,1200m freestyle,M,Silver
...,...,...,...,...,...,...,...,...,...
GRE,Beijing,2008,Rowing,Rowing,"POLYMEROS, Vasileios",Men,lightweight double sculls (2x),M,Silver
GRE,Beijing,2008,Sailing,Sailing,"BEKATOROU, Sofia",Women,Yngling - Keelboat,W,Bronze
GRE,Beijing,2008,Sailing,Sailing,"KRAVARIOTI, Virginia",Women,Yngling - Keelboat,W,Bronze
GRE,Beijing,2008,Sailing,Sailing,"PAPADOPOULOU, Sofia",Women,Yngling - Keelboat,W,Bronze
GRE,Beijing,2008,Taekwondo,Taekwondo,"NIKOLAIDIS, Alexandros",Men,+ 80 kg,M,Silver

In [71]:
oly.reset_index(inplace=True)

In [72]:
oly[oly.City == 'Athens']

,NOC,City,Edition,Sport,Discipline,Athlete,Gender,Event,Event_gender,Medal
0,HUN,Athens,1896,Aquatics,Swimming,"HAJOS, Alfred",Men,100m freestyle,M,Gold
1,AUT,Athens,1896,Aquatics,Swimming,"HERSCHMANN, Otto",Men,100m freestyle,M,Silver
2,GRE,Athens,1896,Aquatics,Swimming,"DRIVAS, Dimitrios",Men,100m freestyle for sailors,M,Bronze
3,GRE,Athens,1896,Aquatics,Swimming,"MALOKINIS, Ioannis",Men,100m freestyle for sailors,M,Gold
4,GRE,Athens,1896,Aquatics,Swimming,"CHASAPIS, Spiridon",Men,100m freestyle for sailors,M,Silver
...,...,...,...,...,...,...,...,...,...,...
27169,EGY,Athens,2004,Wrestling,Wrestling Gre-R,"GABER IBRAHIM, Karam",Men,84 - 96kg,M,Gold
27170,GEO,Athens,2004,Wrestling,Wrestling Gre-R,"NOZADZE, Ramaz",Men,84 - 96kg,M,Silver
27171,USA,Athens,2004,Wrestling,Wrestling Gre-R,"GARDNER, Rulon",Men,96 - 120kg,M,Bronze
27172,RUS,Athens,2004,Wrestling,Wrestling Gre-R,"BAROEV, Khasan",Men,96 - 120kg,M,Gold
27173,KAZ,Athens,2004,Wrestling,Wrestling Gre-R,"TSURTSUMIA, Georgiy",Men,96 - 120kg,M,Silver

In [84]:
oly.iloc[[True]]

IndexError: Boolean index has wrong length: 1 instead of 29216